### PR TITLE
docs(azure-functions) Add Azure Functions plugin

### PR DESCRIPTION
**Pull request by Tieske**
New plugin: https://github.com/Kong/kong-plugin-azure-functions

### Checklist:

- [x] [Commit message & atomicity](https://github.com/Kong/getkong.org/blob/master/CONTRIBUTING.md#commit-atomicity) checked
- [x] Documentation 
- [x] Spellchecked my updates
- [x] Ready to be merged 
- [ ] add it to the konghq.com plugin hub, including the icon
- [x] upload the rock to LuaRocks

### CODE REVIEW

**Comment by Tieske** [comment]
@thibaultcha done.

**Comment by darrenjennings** [comment]
Can this be merged since it is now part of EE 0.32?

**Comment by thibaultcha** [comment]
@darrenjennings Good point, but then this needs to be merged into the master branch instead. On top of that, the installation section should mention that the plugin is bundled with EE 0.32 (and later CE 0.14), otherwise this step is an unnecessary burden for users.

**Comment by darrenjennings** [comment]
@thibaultcha we put a similiar "wait for CE" note on zipkin at the top so I'm good with changing the branch and merging now. There is a small issue that the note is buried a bit since we have the jekyll plugin template: https://getkong.org/plugins/zipkin/ but hopefully this will not be the case for very long and if a user is frustrated by it only being in EE then we can always direct them to the source code since it is publicly available.

**Comment by darrenjennings** [comment]
@Tieske if you remove the 0.14x specific docs then I will be happy to merge this into master and put up a thumbnail on konghq.com

**Comment by Tieske** [comment]
@darrenjennings recreated it as #723

**Pull request closed without merging**
