### PR TITLE
Doc/ee ratelimit updates

### PR DESCRIPTION
**Pull request by rainest**
### Summary
Minor updates to EE Rate Limiting plugin docs.

### Checklist:
- [x] [Commit message & atomicity](https://github.com/Kong/getkong.org/blob/master/CONTRIBUTING.md#commit-atomicity) checked
- [x] Documentation
- [x] Spellchecked my updates
- [x] Ready to be merged

### CODE REVIEW

**Comment by coopr** [comment]
Ideally this includes more clarity on the point that sliding window rate limiting, as we've implemented it, imposes a limit on the **rate** of requests, unlike fixed window, which imposes a limit on the count of requests (per window).

**Comment by darrenjennings** [comment]
@coopr do you need changes or are we good to merge?

**Comment by catfishbluefish** [comment]
Attempting to clear through stalled PR's -- any updates on this?

**Comment by rainest** [comment]
Please merge as is.

**Pull request merged**
