### PR TITLE
doc(plugins) show acl explanation only on authentication plugins

### PR DESCRIPTION
**Pull request by kikito**

### CODE REVIEW

**Comment by hishamhm** [comment]
I thought you were going to add an extra boolean to non-ACL auth plugins to enable that paragraph. Didn't want to over-DRY it?

**Comment by kinman** [comment]
Or, introduce another configuration if and only if the next authentication plugin fails to include the ACL paragraph.

**Comment by kikito** [comment]
> I thought you were going to add an extra boolean to non-ACL auth plugins to enable that paragraph. Didn't want to over-DRY it?

I think this was on the limit. I didn't feel strongly about any of the two options, so I decided to use what we had.

**Comment by coopr** [comment]
Does this need to be added to EE auth plugin pages too?

**Pull request merged**
